# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  workflow_dispatch:
    

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: '5ee5bf3463f5b64419723fcb3fb71ec0'
          projectName: 'mjawash'
          directory: 'out'
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'
